// <auto-generated />
using System;
using EnvisionwareLoader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnvisionwareLoader.Data.Migrations
{
    [DbContext(typeof(ReportingContext))]
    partial class ReportingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnvisionwareLoader.Data.Branch", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.HasKey("Code");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("EnvisionwareLoader.Data.DailySummary", b =>
                {
                    b.Property<DateTime>("Date");

                    b.Property<string>("Branch")
                        .HasMaxLength(50);

                    b.Property<int>("MaxMinutes");

                    b.Property<int>("Minutes");

                    b.HasKey("Date", "Branch");

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("EnvisionwareLoader.Data.HourlySummary", b =>
                {
                    b.Property<DateTime>("Date");

                    b.Property<string>("Branch")
                        .HasMaxLength(50);

                    b.Property<int>("MaxMinutes");

                    b.Property<int>("Minutes");

                    b.HasKey("Date", "Branch");

                    b.ToTable("HourlySummaries");
                });

            modelBuilder.Entity("EnvisionwareLoader.Data.UsageDetail", b =>
                {
                    b.Property<int>("Key");

                    b.Property<string>("Area")
                        .HasMaxLength(50);

                    b.Property<string>("Branch")
                        .HasMaxLength(50);

                    b.Property<int>("Minutes");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Key");

                    b.ToTable("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
